### ISSUE TITLE
Parsing errors when trying to edit or verify swagger.yaml containing x-a127-services service provider references

### ISSUE THREAD

**Issue by jcferrer** [apigee-127/a127#35]
I am getting an error like:

```
rawMessage: 'Reference "volosOAuth" does not exist'
parsedLine: 23
snippet: 'oauth2: *volosOAuth'
parsedFile:  .....
message: 'Reference "volosOAuth" does not exist in  ....... at line 23 (near "oauth2: *volosOAuth")'
```
* swagger.yaml contains something like:
```
x-a127-config:
  oauth2: &volosOAuth
  quota: &volosQuota
  cache: &volosCache
x-a127-services:
  oauth2: *volosOAuth
  quota: *volosQuota
  cache: *volosCache
```
* default.yaml contains something like:
```
oauth2:
  provider: volos-oauth-redis
  options:
    encryptionKey: 'abc123'
    host: 'localhost'
    port: 6379
    tokenLifetime: 300000
    validGrantTypes:
      - client_credentials
      - authorization_code
      - implicit_grant
      - password    
    tokenPaths:  # These will be added to your paths section for you
      authorize: /authorize
      token: /access_token
      invalidate: /invalidate
      refresh: /refresh

cache:
  provider: volos-cache-memory
  options:
    name: weather
    ttl: 60000

quota:
  provider: volos-quota-memory
  options:
    timeUnit: minute
    interval: 1
    allow: 5
```

* Note: Swagger tools work just fine, but I am unable to edit.

Thanks
